apiVersion: apps/v1
kind:  DaemonSet
metadata:
  name: cwatchagent
  labels:
    app: cwatchagent
spec:
  selector:
    matchLabels:
      app: cwatchagent
  template:
    metadata:
      name: cwatchagent
      labels:
        app: cwatchagent
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

