apiVersion: v1
kind: Pod
metadata:
  name: nginxnp
  labels:
    app: nginxnp
spec:
  containers:
  - nmae: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata: 
  name: nodeport
  namespace: amazonns
  labels:
    app: nodeport
spec:
  selector:
    app: nginxnp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort

---

apiVersion: v1
kind: Namespace
metadata:
  name: amazonns
  labels:
    app: amazonns