apiVersion: apps/v1 
kind: ReplicaSet
metadata: 
  name: rsml
  labels:
    app: rsml
spec:
  selector:
    matchLabels:
    app: nginx
  replicas: 3
  template:
    metadata:
      name: nginx-ml
      labels:
      app: nginx-ml
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80